### ISSUE TITLE
50 Point Bonus Always

### ISSUE THREAD

**Issue by TRM13** [Scrabble3D/4.0#1]
Okay this is more of a "feature" than a bug LOL. 
Version 4.02 running on Linux (Kubuntu KDE) 22.04.1 LTS

I place all 7 letters at the end of a word and then click "No" to the pop up box informing me I have a non-dictionary word. I then play anything and get the 50 point bonus. The computer always gets 400-500 and I always get 200-300 but with a little help from a bug I got 843 points!!!!! Win!!!! I've stopped and restarted the program and same result so it should be reproducible. 

https://i.postimg.cc/tJM0Qxrr/Bug-One-843-Points-For-Me.png    # Game board and last part of score sheet
https://i.postimg.cc/NfZhdR2F/Bug-Two-843-Points-For-Me.png   # First part of score sheet

**Comment by HeikoTietze** [comment]
Let's rather remove this cheating "feature" :-). Thanks for reporting, I've tracked down the issue and it will be fixed with the next version.

**Comment by HeikoTietze** [comment]
Resolved with 4.0.3
