### ISSUE TITLE
Scrabble3D V4 errors

### ISSUE THREAD

**Issue by chezdom** [Scrabble3D/4.0#2]
HI,
I manage (at last, cuz I'm a total newbee in Qt and Qt Creator) to compile Scrabble3D. When I try to launch it, here are the message returned in the terminal:
QQmlApplicationEngine failed to load component
qrc:/mainwindow.qml:228:5: Type ScrConfig unavailable
qrc:/ScrConfig.qml:439:21: Type ConfigLetter unavailable
qrc:/ConfigLetter.qml:122:13: Cannot assign to non-existent property "resizableColumns"

mainwindow.qml line 228 and following:
FileDialog {
        id: fileDialog                                                                                                          **Unknown component (M300)**
        folder: StandardPaths.writableLocation(StandardPaths.DocumentsLocation)
        nameFilters: [qsTr("Scrabble3D savegame (*.ssg)"), qsTr("All files (*)")]
        defaultSuffix: "ssg"
        onAccepted: fileMode === FileDialog.OpenFile
                        ? doLoad(file)
                        : GamePlay.saveGame(file)}

    ScrDefaults    { id: defaults }
    ScrNewGame     { id: newgame }
    ScrWordSearch  { id: dictionary }
    ScrAbout       { id: about }
    ScrNetwork     { id: network }
    ScrRemoteGames { id: remotegames}
    ScrConfig      { id: config } //needs to come last trigger system palette change (...)

ScrConfing.qml line 439 and following:
ConfigLetter {
                        id: configLetter
                        visible: lView.currentIndex === 1
                        onVisibleChanged: {
                            scrollView.contentHeight = configLetter.height
                            scrollView.contentWidth = configLetter.width
                        }

ConfigLetter.qml line 122 and following:
resizableColumns: false                                                                  **Invalid property name "resizableColumns". (M16)**
            model: [qsTr("Letter"), qsTr("Points"), qsTr("Count")]
            delegate: Rectangle {
                implicitWidth: text.implicitWidth
                implicitHeight: Math.max(horizontalHeader.height,
                                         text.implicitHeight + 4)
                color: myPalette.mid
                border.color: myPalette.midlight (...)

note that in ScrConfig.qml, many "unknown component" occur at lines 238, 242, 246, 330, 332 to 338

I compiled under Linx Mint 21.2 and Qt 6.5.2

Any idea ?

**Comment by Scrabble3D** [comment]
resizableColumns requires version 6.5+. it's needed because of https://bugreports.qt.io/browse/QTBUG-115001. I suggest to review your Qt configuration (always an annoyance to me too).
