### ISSUE TITLE
French localization

### ISSUE THREAD

**Issue by chezdom** [Scrabble3D/4.0#4]
Hi, I've finished the french localization of Scrabble3D, but I don't know how to upload the .qm file in the localizations repository.
Can you help me ?
Thx in advance

**Comment by Scrabble3D** [comment]
Thanks a lot for your contribution! Please work on or upload to Transifex. That allows others to join the localization team, and eventually me to download the content. I'll convert the file then [1] and upload it to the Github repository so French would be available for everyone.

**Comment by chezdom** [comment]
Done !On transifex.com
    Le samedi 25 novembre 2023 à 09:51:43 UTC+3, Scrabble3D ***@***.***> a écrit :  
 
 


Thanks a lot for your contribution! Please work on or upload to Transifex. That allows others to join the localization team, and eventually me to download the content. I'll convert the file then [1] and upload it to the Github repository so French would be available for everyone.

**Comment by Scrabble3D** [comment]
And added as v1.0.1 to the repository. IIRC, the program updates weekly, but you can force a pull by deleting the file .config/Scrabble3D/4/Scrabble3D.conf.

Merci bien!
