### ISSUE TITLE
Cannot override FINAL property

### ISSUE THREAD

**Issue by papoteur-mga** [Scrabble3D/4.0#5]
Hello,
I have build the project in Mageia cauldon, with Qt6.6.0
I get this error at launch:
Scrabble3D 
QQmlApplicationEngine failed to load component
qrc:/mainwindow.qml:228:5: Type ScrConfig unavailable
qrc:/ScrConfig.qml:439:21: Type ConfigLetter unavailable
qrc:/ConfigLetter.qml:175:21: Cannot override FINAL property

**Comment by Scrabble3D** [comment]
Please uncomment "resizableColumns: false" at line 122 in ConfigLetter.qml. This property requires Qt 6.5, see https://bugreports.qt.io/browse/QTBUG-115001 for details.

**Comment by papoteur-mga** [comment]
Hello,
I use the code in the latest snapshot, thus this line is already uncommented:
https://github.com/Scrabble3D/4.0/blob/dde13b089c0c03934c3943b3e80289f59e16f8dd/ConfigLetter.qml#L122

Do you mean comment?

**Comment by Scrabble3D** [comment]
Yes, of course comment out ;-)

**Comment by papoteur-mga** [comment]
However, I still have the same error

**Comment by papoteur-mga** [comment]
The line to comment is line 175.
I can start now.
